// This component was generated by @sitecore-search/cli on Tue Mar 25 2025 09:33:46 GMT+0100 (Central European Standard Time)

import { keyframes, styled } from 'styled-components';

import { theme } from '@sitecore-search/ui';

const Rotate = keyframes`
  from {
      transform: rotate(0deg);
  }
  to {
      transform: rotate(360deg);
  }
`;

export const LoaderAnimation = styled.svg`
  animation: ${Rotate} 2s linear infinite;
  display: block;
  color: ${theme.vars.palette.text.primary};
  height: 50px;
  margin: auto;
  width: 50px;
`;

export const LoaderContainer = styled.div`
  align-items: center;
  display: flex;
  position: absolute;
  left: 0;
  right: 0;
  height: 100%;
  background-color: white;
  opacity: 0.5;
  z-index: 100;
`;
