// This component was generated by @sitecore-search/cli on Tue Mar 25 2025 09:33:46 GMT+0100 (Central European Standard Time)

import type { ChangeEvent } from 'react';
import { useCallback } from 'react';

import type { PreviewSearchInitialState } from '@sitecore-search/react';
import { WidgetDataType, usePreviewSearch, widget } from '@sitecore-search/react';
import { Presence, PreviewSearch } from '@sitecore-search/ui';

import Spinner from '../../../../components/Spinner';
import SuggestionBlock from '../../../../components/SuggestionBlock';
import { ArticleCardStyled, PreviewSearchStyled } from './styled';

const DEFAULT_IMG_URL = 'https://placehold.co/500x300?text=No%20Image';

type ArticleModel = {
  id: string;
  name?: string;
  title?: string;
  image_url: string;
  url: string;
  source_id?: string;
};

type InitialState = PreviewSearchInitialState<'itemsPerPage' | 'suggestionsList'>;

interface PreviewSearchProps {
  defaultItemsPerPage: number | 6;

  /**
   * An optional custom redirection handler that will be called when the user clicks on an article.
   * You can use your own redirection logic here, or any other side effect.
   * Examples
   * * (article: Article) => history.push(`/search?q=${article.id}`);
   * * (article: Article) => window.location.href = `/search?q=${article.id}`;
   * * (article: Article) => setRoute(`/custom/search/endpoint?q=${article.id}`);
   * @param article The article that was clicked.
   */
  itemRedirectionHandler?: (article: ArticleModel) => void;

  /**
   * An optional custom submit handler that will be called when the user submits the form by pressing the enter key.
   * You can use your own submit logic here, or any other side effect.
   * Most common use case is to redirect the user to a custom search page with the query string.
   * Examples
   * * (query: string) => history.push(`/search?q=${query}`);
   * * (query: string) => window.location.href = `/search?q=${query}`;
   * * (query: string) => setRoute(`/custom/search/endpoint?q=${query}`);
   * @param query The query string that was submitted.
   */
  submitRedirectionHandler?: (query: string) => void;
}

export const PreviewSearchComponent = ({
  defaultItemsPerPage = 6,
  itemRedirectionHandler,
  submitRedirectionHandler,
}: PreviewSearchProps) => {
  const {
    widgetRef,
    actions: { onItemClick, onKeyphraseChange },
    queryResult,
    queryResult: {
      isFetching,
      isLoading,
      data: { suggestion: { title_context_aware: articleSuggestions = [] } = {} } = {},
    },
  } = usePreviewSearch<ArticleModel, InitialState>({
    state: {
      suggestionsList: [{ suggestion: 'auto_named_suggester_4', max: 10 }],
      itemsPerPage: defaultItemsPerPage,
    },
  });

  const loading = isLoading || isFetching;
  const keyphraseHandler = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      const target = event.target;
      onKeyphraseChange({ keyphrase: target.value });
    },
    [onKeyphraseChange]
  );
  return (
    <PreviewSearchStyled.Root>
      <PreviewSearchStyled.Form
        onSubmit={(e) => {
          e.preventDefault();
          const { value: query } = e.currentTarget.elements[0] as HTMLInputElement;
          // eslint-disable-next-line @typescript-eslint/no-unused-expressions
          submitRedirectionHandler && submitRedirectionHandler(query);
        }}
      >
        <PreviewSearchStyled.Input
          onChange={keyphraseHandler}
          autoComplete="off"
          placeholder="Type to search..."
          data-testid="contentPSLeftInput"
        />
      </PreviewSearchStyled.Form>
      <PreviewSearchStyled.Content ref={widgetRef}>
        <Presence present={loading}>
          <Spinner />
        </Presence>
        <Presence present={!loading}>
          <>
            {articleSuggestions.length > 0 && (
              <PreviewSearchStyled.Suggestions>
                <SuggestionBlock
                  blockId={'title_context_aware'}
                  items={articleSuggestions}
                  title={'Suggestions'}
                />
              </PreviewSearchStyled.Suggestions>
            )}
            <PreviewSearch.Results defaultQueryResult={queryResult}>
              {({ isFetching: loading, data: { content: articles = [] } = {} }) => (
                <PreviewSearchStyled.Items data-loading={loading} data-testid="contentPSResults">
                  <Presence present={loading}>
                    <Spinner />
                  </Presence>
                  {!loading &&
                    articles.map((article, index) => (
                      <PreviewSearchStyled.Item
                        key={article.id}
                        asChild
                        data-testid="psContentItem"
                      >
                        <PreviewSearchStyled.Link
                          href={article.url}
                          onClick={() => {
                            // onItemClick is for tracking purposes
                            onItemClick({ id: article.id, index, sourceId: article.source_id });
                            // eslint-disable-next-line @typescript-eslint/no-unused-expressions
                            itemRedirectionHandler && itemRedirectionHandler(article);
                          }}
                        >
                          <ArticleCardStyled.Root>
                            <ArticleCardStyled.ImageWrapper>
                              <ArticleCardStyled.Image src={article.image_url || DEFAULT_IMG_URL} />
                            </ArticleCardStyled.ImageWrapper>
                            <ArticleCardStyled.Name>
                              {article.name || article.title}
                            </ArticleCardStyled.Name>
                          </ArticleCardStyled.Root>
                        </PreviewSearchStyled.Link>
                      </PreviewSearchStyled.Item>
                    ))}
                </PreviewSearchStyled.Items>
              )}
            </PreviewSearch.Results>
          </>
        </Presence>
      </PreviewSearchStyled.Content>
    </PreviewSearchStyled.Root>
  );
};
const PreviewSearchWidget = widget(
  PreviewSearchComponent,
  WidgetDataType.PREVIEW_SEARCH,
  'content'
);
export default PreviewSearchWidget;
