// This component was generated by @sitecore-search/cli on Tue Mar 25 2025 09:33:46 GMT+0100 (Central European Standard Time)

import { usePreviewSearchActions } from '@sitecore-search/react';

import { SearchGroupHeadingStyled, SuggestionGroupStyled } from './styled.js';

type SuggestionBlockProps = {
  items: Array<{ text: string }>;
  title: string;
  blockId: string;
  filterAttribute?: string;
  disabled?: boolean;
};

const SuggestionBlock = ({ items, title, blockId, filterAttribute, disabled }: SuggestionBlockProps) => {
  const { onSuggestionClick } = usePreviewSearchActions();
  return (
    <>
      {items.length > 0 && (
        <SuggestionGroupStyled.Root id={blockId} filterAttribute={filterAttribute}>
          <SearchGroupHeadingStyled>{title}</SearchGroupHeadingStyled>
          {items.map(({ text }) => (
            <SuggestionGroupStyled.Trigger id={text} key={text} disabled={disabled} asChild>
              <a
                onClick={() => {
                  onSuggestionClick({
                    name: blockId,
                    title,
                    value: text,
                    displayName: text,
                  });
                }}
              >
                {text}
              </a>
            </SuggestionGroupStyled.Trigger>
          ))}
        </SuggestionGroupStyled.Root>
      )}
    </>
  );
};

export default SuggestionBlock;
