// This component was generated by @sitecore-search/cli on Tue Mar 25 2025 09:33:46 GMT+0100 (Central European Standard Time)

import { styled } from 'styled-components';

import { PreviewSearch, theme } from '@sitecore-search/ui';

export const SearchGroupHeadingStyled = styled.h2`
  box-sizing: border-box;
  padding-left: ${theme.vars.spacing.s};
`;

const SuggestionGroupRootStyled = styled(PreviewSearch.SuggestionsGroup)`
  flex: 1;
  display: flex;
  flex-direction: column;
`;

const SuggestionGroupTriggerStyled = styled(PreviewSearch.SuggestionTrigger)`
  cursor: pointer;
  padding: ${theme.vars.spacing.s} ${theme.vars.spacing.s};

  &[data-state='active'],
  &:focus,
  &:hover {
    outline: none;
    font-weight: bold;
    background: #fff;
  }
`;

export const SuggestionGroupStyled = {
  Root: SuggestionGroupRootStyled,
  Trigger: SuggestionGroupTriggerStyled,
};
